# Generated by Django 3.2.12 on 2025-01-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250111_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.userprofile'),
        ),
    ]
